export default [
    {
      "quizId": "001",
      "courseId": "RS101",
      "title": "Introduction to React",
      "quizType": "Graded Quiz",
      "points": 50,
      "assignmentGroup": "Quizzes",
      "shuffleAnswers": true,
      "timeLimit": 20,
      "multipleAttempts": false,
      "howManyAttempts": 1,
      "showCorrectAnswers": "Immediately",
      "accessCode": "",
      "oneQuestionAtATime": true,
      "webcamRequired": false,
      "lockQuestionsAfterAnswering": false,
      "dueDate": "2024-12-15T00:00",
      "availableDate": "2024-12-01T00:00",
      "untilDate": "2024-12-20T00:00",
      "questions": [],
      "published": true
    },
    {
      "quizId": "002",
      "courseId": "RS101",
      "title": "Advanced JavaScript Concepts",
      "quizType": "Practice Quiz",
      "points": 30,
      "assignmentGroup": "Exams",
      "shuffleAnswers": false,
      "timeLimit": 30,
      "multipleAttempts": true,
      "howManyAttempts": 3,
      "showCorrectAnswers": "Immediately",
      "accessCode": "JS2024",
      "oneQuestionAtATime": true,
      "webcamRequired": true,
      "lockQuestionsAfterAnswering": true,
      "dueDate": "2024-12-20T00:00",
      "availableDate": "2024-12-10T00:00",
      "untilDate": "2024-12-25T00:00",
      "questions": [],
      "published": true
    },
    {
      "quizId": "003",
      "courseId": "RS101",
      "title": "Data Structures and Algorithms",
      "quizType": "Graded Survey",
      "points": 75,
      "assignmentGroup": "Assignments",
      "shuffleAnswers": true,
      "timeLimit": 60,
      "multipleAttempts": true,
      "howManyAttempts": 2,
      "showCorrectAnswers": "Immediately",
      "accessCode": "",
      "oneQuestionAtATime": false,
      "webcamRequired": false,
      "lockQuestionsAfterAnswering": true,
      "dueDate": "2024-11-30T00:00",
      "availableDate": "2024-11-15T00:00",
      "untilDate": "2024-12-05T00:00",
      "questions": [],
      "published": true
    },
    {
      "quizId": "004",
      "courseId": "RS101",
      "title": "HTML and CSS Basics",
      "quizType": "Ungraded Survey",
      "points": 20,
      "assignmentGroup": "Project",
      "shuffleAnswers": false,
      "timeLimit": 0, 
      "multipleAttempts": false,
      "howManyAttempts": 1,
      "showCorrectAnswers": "Immediately",
      "accessCode": "",
      "oneQuestionAtATime": false,
      "webcamRequired": false,
      "lockQuestionsAfterAnswering": false,
      "dueDate": "2024-12-01T00:00",
      "availableDate": "2024-11-20T00:00",
      "untilDate": "2024-12-10T00:00",
      "questions": [],
      "published": true
    },
    {
      "quizId": "005",
      "courseId": "RS101",
      "title": "Database Management Systems",
      "quizType": "Graded Quiz",
      "points": 100,
      "assignmentGroup": "Quizzes",
      "shuffleAnswers": true,
      "timeLimit": 45,
      "multipleAttempts": true,
      "howManyAttempts": 5,
      "showCorrectAnswers": "Immediately",
      "accessCode": "DB2024",
      "oneQuestionAtATime": true,
      "webcamRequired": true,
      "lockQuestionsAfterAnswering": true,
      "dueDate": "2024-12-25T00:00",
      "availableDate": "2024-12-15T00:00",
      "untilDate": "2025-01-05T00:00",
      "questions": [],
      "published": true
    }
  ];